#! /bin/bash
set -eu -o pipefail
shopt -s extglob nullglob globstar

main() {
  # Check for installed depencies first #
  depCheck

  ########## global vars ##########

  # make temp working dir #
  local -r tmpdir="$(mktemp -d /tmp/resize.XXXXXXXXXXXX)/"

  # set defualt output dir #
  local -r outdir="$HOME/FFVII_FRP/"
  mkdir -p "$outdir"

  # set default input dir #
  local -r indir="$HOME/FFVII_fields/"

  # make an array of scene dirs in $indir #
  local -a -r scenes=("${indir}"[a-z]*_batch/)

  # the composites of working layers #
  local -r composite="${tmpdir}composite.png"
  local -r comp_out="${composite%.png}_out.png"
  local -r comp_aux="${tmpdir}comp_aux.png"

  ########## main loop ##########

  # set trap for clean exit #
  trap finish EXIT

  for scene in "${scenes[@]}"
    do
      # get basename without calling external basename with parameter expn #
      local outscene="$outdir${scene#${scene%/*/}/}"
      mkdir -p "$outscene"

      cd "$scene"

      # capture size of base image #
      local size
      size=$(identify -format "%wx%h" -- *000.png)

      # fairly explicit globbing to weed out false positives #
      local -a mLays aLays
      mLays=( [a-z]*_[0-2]_000@(001*|*000).png )
      aLays=( [a-z]*_[0-2]_000!(001*|[6-9]*|*000.)png )

      # process main layers #
      if [[ -n "${mLays[@]}" ]]; then
      mainLay "mLays"
      fi

      # if there are any aux layers handle them #
      if [[ -n "${aLays[@]}" ]]; then
        auxLay
      fi

      # cleanup temp dir #
      rm "$tmpdir"*
    done
}

# simple dependency check #
function depCheck {
  local -a deps
  deps=(
  "waifu2x-converter-cpp"
  "convert"
  "composite"
  "identify"
  "potrace"
  )

  for dep in "${deps[@]}"; do
    if [[ -z $(command -v "$dep") ]]
    then
      printf "Error: '%s' not found\n" "$dep" >&2 && exit 1
    fi
  done
}

# $PHOTOMOD is waifu2x model dir held in an env var#
function scale {
  local output input

  if [[ -a "$comp_aux" ]]
    then
      output="$comp_aux"
      input="$comp_aux"
    else
      output="$comp_out"
      input="$composite"
  fi
      waifu2x-converter-cpp \
        --scale_ratio 4 \
        --model_dir \
        "$PHOTOMOD" \
        -m scale \
        -i "$input" \
        -o "$output" > /dev/null
}


# produces the main layers #
function mainLay {
  local -n files
  files="$1"

  convert -size "$size" xc:black "$composite"

  # compose layers into single image #
  for file in "${files[@]}"
    do
      composite "$file" "$composite" "$composite"
    done

  # scale and put base layer in output dir #
  scale
  cp "$comp_out" "$outscene${files[0]}"

  # process remaining main layers from base #
  cutLayer "${!files}"
  noOverlap "${files[@]}"
}

# handle the auxilary layers one at a time #
function auxLay {
  for aLay in "${aLays[@]}"
    do
      # compose the main composite with one aux layer #
      composite "$aLay" "$composite" "$comp_aux"

      # scale the result #
      scale

      cutLayer "aLay"

      # send only three values to avoid duplicate processing #
      noOverlap "${mLays[@]:(-2)}" "$aLay"
    done
}

# produce the enlarged layers #
function cutLayer {
  local -n files
  local pbm svg mask input
  files="$1"

  for file in "${files[@]}"
    do
      if [[ "$file" != *000.png ]]
        then
          # vars for current and temp files #
          pbm="$tmpdir${file%png}pbm"
          svg="$tmpdir${file%png}svg"
          mask="$tmpdir${file%.png}_mask.png"

          # fill opacity with white; transparency with black... #
          convert "$file" \
            -fuzz 100% \
            -fill white \
            -opaque green \
            -background black \
            -alpha remove \
            "$pbm"

          # produce vector trace... #
          potrace -a 0 -b gimppath -x 3.2 \
            "$pbm" > "$svg"

          # rasterize and remove semi-transparent pixels... #
          convert -background none \
            "$svg" \
            -channel A \
            -threshold 1% \
            "$mask"

          # subtract from base image and place in outdir #
          if [[ -a "$comp_aux" ]]
            then
              input="$comp_aux"
            else
              input="$comp_out"
          fi

          convert "$input" "$mask" \
            -gravity center \
            -compose CopyOpacity \
            -composite -channel A \
            -negate "$outscene$file"
      fi
    done
}

# ensure layers do not share pixels #
function noOverlap {
  local -a files
  files=("$@")

  # ensure the base image is not processed #
  for (( i=${#files[@]}-1; i > 1; i-- ))
    do
      # return first input image minus shared pixels #
      convert "$outscene${files[$i]}" "$outscene${files[$i-1]}" \
        -compose Change-mask \
        -composite "$outscene${files[$i]}"
    done
}

# cleanup temp dir #
function finish {
  rm -r "$tmpdir"
}

main
